### ISSUE TITLE
problem with item draw

### ISSUE THREAD

**Issue by lllWinchesterlll** [JackMD/MysteryCrate#79]
during the draw of items, it is possible to remove the items by clicking several times on them, and if a player repeatedly hits the box it breaks the floating text!

**Comment by JackMD** [comment]
>during the draw of items, it is possible to remove the items by clicking several times on them

I cannot reproduce this error. If it does happen then its not the plugins fault. Also only one time I managed to reproduce this error but when I tried using the item it was taken away from the inventory.

>if a player repeatedly hits the box it breaks the floating text

I cannot reproduce this either. Out of all the people who use this plugin you are the only one complaining about it. And so I am 100% sure that it occurs (only if it occurs) due to someother protection plugin. Test this plugin without having anyother plugins installed and it will not occur.

**Comment by JackMD** [comment]
Okay I managed to reproduce this
>if a player repeatedly hits the box it breaks the floating text

**Comment by JackMD** [comment]
#77

**Comment by JackMD** [comment]
Hopefully players can no longer destroy the floating text. Please confirm this and let me know
